--- ira/Makefile	2015-09-11 09:25:13.000000000 +0200
+++ ira/Makefile	2015-09-11 09:21:37.000000000 +0200
@@ -2,7 +2,7 @@
 EXT	=
 CC	= gcc
 CCOUT	= -o 
-COPTS	= -c -O2
+COPTS	= -c -O2 -Wall -Wno-pointer-sign -Wno-unused-result
 LD	= $(CC)
 LDOUT	= $(CCOUT)
 LDFLAGS	=
