CC = gcc
CFLAGS = -O2 -Wall -I../target/include -I../target/m68k-amigaos/sys-include

all:  GccFindHit hunk2aout

GccFindHit.o: GccFindHit.c defs.h
hunk2aout.o: hunk2aout.c

clean: GccFindHit hunk2aout
